# Config format schema number
format_version: 4

###################
## Model options
model_params:
  model_architecture: "cylinder_asym"

  # Grid size of each voxel
  output_shape:
    - 480
    - 360
    - 32

  fea_dim: 9
  out_fea_dim: 256

  # Number of classes
  num_class: 20
  num_input_features: 16
  use_norm: True
  init_size: 16

###################
## Dataset options
dataset_params:
  dataset_type: "cylinder_dataset"
  pc_dataset_type: "SemKITTI_sk"
  ignore_label: 0
  return_test: False
  fixed_volume_space: True
  label_mapping: "./config/label_mapping/semantic-kitti.yaml"
  max_volume_space:
    - 50
    - 3.1415926
    - 2
  min_volume_space:
    - 0
    - -3.1415926
    - -4

###################
## Data_loader options
train_data_loader:
  data_path: "/home/volkan/Documents/Codes/sparse-conv-lstm/data/sequences"
  imageset: "train"
  return_ref: True
  batch_size: 1
  shuffle: False
  num_workers: 0

val_data_loader:
  data_path: "/home/volkan/Documents/Codes/sparse-conv-lstm/data/sequences"
  imageset: "val"
  return_ref: True
  batch_size: 1
  shuffle: False
  num_workers: 0

###################
## Train params
train_params:
  model_load_path: "./models/model_save_backup.pt"
  model_save_path: "./models/model_checkpoint.pt"
  checkpoint_every_n_steps: 1
  max_num_epochs: 10
  eval_every_n_steps: 1
  learning_rate: 0.001
